apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devpulse
  template:
    metadata:
      labels:
        app: devpulse
    spec:
      containers:
        - name: devpulse
          image: yogramming/devpulse:replaceImageTag
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
