apiVersion: v1
kind: Service
metadata:
  name: devpulse-service
  namespace: default
spec:
  selector:
    app: devpulse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
